server:
  port: 8081
  servlet:
    context-path: /bootcamp-samb

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://sgmjfhjhhxugab:28b3107141361ef51403b6c2e61ee174bc486c6b8a572344dd16decba772b978@ec2-34-230-115-172.compute-1.amazonaws.com:5432/de22ubmn36sefi
    username: sgmjfhjhhxugab
    password: 28b3107141361ef51403b6c2e61ee174bc486c6b8a572344dd16decba772b978
  jpa:
    show-sql: true
    database-plataform: org.hibernate.dialect.PostgreSQLDialect
    general-dll: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander
  version: 1.0